### ISSUE TITLE
Depixelator is not working?

### ISSUE THREAD

**Issue by otanim** [reMarkable/depixelator#3] opened 2020-08-28 00:16 UTC
Hi,
due to your repositories, nor software architecture is not documented enough and due to your support team didn't have responded to my messages (twice) I think this could be the right place to report about the issue that I'm having.

If this repository's project is responsible for depixelization, then I'm "happy" to tell you that after I've upgraded my RM1 to version `1.6.0.6` from `1.5.x.x`, it caused writing to be all pixelated as you have in your `simple.png` ![simple.png](https://github.com/reMarkable/depixelator/blob/master/simple.png?raw=true)  file.

Hope you/your dev team can check on this issue, let me know if I need to provide you any logs or data from my RM1's memory for the debugging.

**Comment by sletta** [comment] 2020-08-28 08:38
The depixelator module is related to vectorization og raster images, typically in the conversion of pixels to vector graphics. I don't think it relates to the problem you are describing. I suggest upgrading to a more recent version and then keep trying support.

**Comment by otanim** [comment] 2020-08-28 09:10
Hi @sletta, thanks for the quick response. Sorry for posting an unrelated topic here.

> I suggest upgrading to a more recent version and then keep trying support.
I keep updating my RM1's version since 1.6.0.x version (Oct-2018) till the latest 2.2.0.x version (Aug-2020). Apparently I'm the only one, or only a few people reported about this issue, so no one in support's team bothered to properly deliver this to tech people. Reported once in 2018, then in 2019, will try again. But the support team/the communication with the customers definitely needs to be improved...

**Comment by sandsmark** [comment] 2020-08-28 10:22
> If this repository's project is responsible for depixelization

As sletta wrote, depixelator is just for converting raster graphics to vector graphics (i. e. when exporting to vector formats like SVG and PDF). https://github.com/reMarkable/quill is responsible for rendering strokes to raster.

That said, I'm not sure about the issue you're having. Because of how the display works the rendering has always been one-bit (and therefore pixelated). Is it during the export you're noticing the regression?

> Apparently I'm the only one, or only a few people reported about this issue, so no one in support's team bothered to properly deliver this to tech team.

Our support team reports all new or novel issues to the product teams.


I'll close this issue (as it isn't relevant to this project), but we'll still get your replies so please provide further information and/or a test-case so we can reproduce it. :-)

**Closed by sandsmark** 2020-08-28 10:22 UTC

**Comment by otanim** [comment] 2020-08-28 11:53
> That said, I'm not sure about the issue you're having. Because of how the display works the rendering has always been one-bit (and therefore pixelated). Is it during the export you're noticing the regression?

It's happening right when I'm trying to use the marker on the screen for writing.

> Our support team reports all new or novel issues to the product teams.

I had a different experience. Hope it's not the same with the others. I even wanted to downgrade my OS's version, got a response that I neither can downgrade, due to it's not "backward-compatible", nor the support team can help because "they can't reproduce the same issue that I'm having".

**Comment by otanim** [comment] 2020-09-15 07:31
Hi @sandsmark, I messaged to your support center on September 4th, I didn't get any response since then. I'm considering canceling my RM2's pre-order. That would've been great if I'll get the reply :)

**Comment by sletta** [comment] 2020-09-18 05:58
Hi @otanim , I checked with the support department and they found one request from you about a website issue from 30.08, but no others. Which email did you send it to and which did you use yourself? Perhaps we can track it down in the system.

**Comment by otanim** [comment] 2020-09-18 06:15
HI @sletta, I didn't have reported anything about the website's issue, or perhaps I've reported about it decades ago. I've reported via my otanim617 [at] gmail.com account.

Yesterday I've sent an order cancellation request, hope they got that one :)
